#!/bin/sh

echo ... stop snmpd ...

if [ -r /run/snmpd.pid ]; then
    snmpd_pid=$(cat /run/snmpd.pid)
    kill -9 ${snmpd_pid}
fi

if [ -f /etc/snmp/snmpd.conf ]; then
    rm /etc/snmp/snmpd.conf
fi

logger -t TEST $0
