#!/bin/sh
# monitor-dev /dev/devname check-timeout

syslog_tag=TERMINAL.$(hostname)

logger -t ${syslog_tag} "Monitor floppy: exec ${0}"

common_opts="nodev,noexec"
ntfs_opts="${common_opts},uid=1000,gid=100,umask=0111,fmask=0111,dmask=0000"
vfat_opts="${common_opts},utf8,iocharset=iso8859-1,uid=1000,gid=100,fmask=0111,dmask=0000"
ext4_opts="${common_opts},nosuid"
xfs_opts="${common_opts},nosuid"
udf_opts="${common_opts},uid=1000,gid=100"
iso_opts="${common_opts},uid=1000,gid=100"
exf_opts="nonempty,uid=1000,gid=100,umask=0111,fmask=0111,dmask=0000"

dev_name=${1}
check_timeout=${2}
# Каталог в /media
media_path=/mnt/media/$(basename ${dev_name})

[ -n "${dev_name}" ]      || exit 1
[ -n "${check_timeout}" ] || exit 1

dev_not_ready () {
    if dd if="${dev_name}" of=/dev/null count=0; then
	return 1
    fi
    return 0
}

mount_media () {
    is_mounted=$(mount | grep "^${dev_name} ")
    if [ -z "${is_mounted}" ]; then
	logger -t ${syslog_tag} "Monitor floppy: ${DEVNAME}"
	ntfs-3g          -o ${ntfs_opts} ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as ntfs-3g"; exit 0; }
	mount.exfat      -o ${exf_opts}  ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as exfat";   exit 0; }
	mount -t vfat    -o ${vfat_opts} ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as vfat";    exit 0; }
	mount -t ext4    -o ${ext4_opts} ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as ext4";    exit 0; }
	mount -t xfs     -o ${xfs_opts}  ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as xfs";     exit 0; }
	mount -t udf     -o ${udf_opts}  ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as udf";     exit 0; }
	mount -t iso9660 -o ${iso_opts}  ${DEVNAME} ${media_path} && { logger -t ${syslog_tag} "Mount floppy: ${DEVNAME} to ${media_path} as iso9660"; exit 0; }
    fi
}

umount_media () {
    # Точка монтирования удаляемого устройства
    mount_point=$(mount | grep "^${dev_name} " | awk '{print $3}')

    if [ -n "${mount_point}" ]; then
        # Каталог в /media и точка монтирования должны совпадать.
	if [ "${media_path}" = "${mount_point}" ]; then
	    logger -t ${syslog_tag} "Monitor floppy: umount ${mount_point} from ${DEVNAME}"
	    umount -lf "${mount_point}"
	fi
    fi
}

while true; do
    if [ ! -e "${dev_name}" ]; then
	umount_media
	exit 0
    fi

    if dev_not_ready; then
	umount_media
    else
	mount_media
    fi

    sleep ${check_timeout}
done
