#!/bin/sh

action=$1

clean_ip () {
    [ -f "/run/network/${interface}/dhcp" ] && rm "/run/network/${interface}/dhcp"
    [ -f "/run/network/${interface}/search" ] && rm "/run/network/${interface}/search"
    [ -f "/run/network/${interface}/nameserver" ] && rm "/run/network/${interface}/nameserver"
    [ -f "/run/network/${interface}/ntpsrv" ] && rm "/run/network/${interface}/ntpsrv"
    [ -f "/run/network/${interface}/rootpath" ] && rm "/run/network/${interface}/rootpath"
}

set_ip () {

    # маршрутизация
    if [ -n  "${router}" ]; then
	route add default gw "${router}"
    fi

    # resolv.conf
    if [ -n  "${domain}" ]; then
	echo "${domain}" > "/run/network/${interface}/search"
    fi
    if [ -n  "${dns}" ]; then
	echo -n > "/run/network/${interface}/nameserver"
	for ns in ${dns}; do
	    echo ${ns} >> "/run/network/${interface}/nameserver"
	done
    fi

    # ntpsrv
    if [ -n  "${ntpsrv}" ]; then
	if [ -f "/run/network/${interface}/ntpsrv" ]; then
	    rm "/run/network/${interface}/ntpsrv"
	fi
	for time_server in ${ntpsrv}; do
	    echo ${time_server} >> "/run/network/${interface}/ntpsrv"
	done
    fi

    # rootpath
    tune=""
    if [ -n  "${rootpath}" ]; then
	tune=$(echo "${rootpath}" | awk -F ',' '{print $1" "$2" "$3" "$4}')
	if [ -n "${tune}" ]; then
	    echo $tune > "/run/network/${interface}/rootpath"
	fi
    fi
}

case ${action} in

    deconfig)
	clean_ip
	ifconfig "${interface}" 0.0.0.0 up
	;;

    bound)
	# сетевой интерфейс
	clean_ip
	if [ -n  "${ip}" ]; then
	    ifconfig "${interface}" "${ip}" netmask "${subnet}" up
	    touch "/run/network/${interface}/dhcp"
	fi
	set_ip
	;;

    renew)
	# обновление ddns
	clean_ip
	set_ip
	/usr/local/bin/ddns "${interface}"
	;;
    *)
	;;

esac

exit 0
