#!/bin/sh

echo ... read config ...

modprobe fuse

union=""
for eth_dev_dir in /run/network/* ; do
    if [ -r "$eth_dev_dir/rootpath" ]; then
	eth_dev=$(basename $eth_dev_dir)
	read conf_root conf_user conf_domain conf_passwd x < "/run/network/$eth_dev/rootpath"
	mkdir -p "/mnt/$eth_dev"
	if [ "$union" == "" ]; then
	    union="/mnt/$eth_dev"
	else
	    union="$union:/mnt/$eth_dev"
	fi
	mount.cifs $conf_root "/mnt/$eth_dev" -o user=$conf_user,domain=$conf_domain,password=$conf_passwd
    fi
done

unionfs-fuse "$union" /mnt/config
