#!/bin/sh

echo ... remote syslogd ...

# DNS-имя сервера, принимающего логи syslogd.
remote_syslog=""

if [ -r /etc/remote-syslog ]; then
    remote_syslog=$(cat /etc/remote-syslog)
fi

# перезапуск syslogd если есть сервер принимающий логи.
if [ -n "$remote_syslog" ]; then
    syslogd_pid=$(cat /var/run/syslogd.pid)
    kill -9 $syslogd_pid
    syslogd -L -R "$remote_syslog"
    unset remote_syslog
fi
